### ISSUE TITLE
Manifest dir does not exist on initial setup

### ISSUE THREAD

**Issue by ipwnosx** [mowzie/discordBots#3]
container@pterodactyl~ Server marked as running...
(node:24) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './manifest/manifest.json'
    at Object.openSync (fs.js:458:3)
    at Object.writeFileSync (fs.js:1355:35)
    at updateManifest (/home/container/bot.js:235:6)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DiscordClient.<anonymous> (/home/container/bot.js:41:9)
(node:24) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mowzie** [comment]
https://github.com/mowzie/destinyClanDiscordBot/commit/db9559456b000209cf7f51d00e5229252f160188
